### PR TITLE
make `RealmStorage` more efficient when getting an item in a `RealmSection`

### PR DESCRIPTION
**Pull request by skydivedan**
`RealmStorage.item(at: IndexPath)` was taking a realm `AnyRealmCollection`, and putting all of it's results into an `Array`. Then it could get the count from that array.

Then, if the `indexPath` was in the range of that count, it would pull all the items into the local array _again_, and get the `nth` item. 

As this could get very ineffecient with a large amount of items, the code was changed to use Realm's own routines to get the the count of items to check the range, `numberOfItems`
To get the actual item in the results, we added in `subscript` to the `Section` protocol. There is a protocol extension to do do the basic `return items[index]`, but in Realm, we don't want to use `items` at all (as it's an Array, and is retrieved by loading in all items from the DB). So, we define that function in `RealmSection`, so that it does this `return results[index]`

**Note to @DenTelezhkin **: I had Cocoapods trouble... it didn't like the the `swift_versions` tag for some reason. I've no idea why, as I (originally) didn't change it. Some weird Cocoapods issue, that other people seem to be happening intermittenly. My guess is that you could load in the changes here,  and un-comment the `swift_version` directive again. I'm using CP 1.6, so I don't really get it.

### CODE REVIEW

**Comment by DenTelezhkin** [comment]
Thanks for catching this issue and taking your time to provide a fix!

I want to do several things prior to fixing this issue on master, namely try to return to actually testing RealmStorage, if I'll be able to turn CI on efficiently again(previously Realm compiled for such a long time that Travis just died every time with timeout). Second - probably we need some perfomance test that shows the problem. And third - it's possible I might deprecate entire `items` property and reintroduce it as a method with different name, to better show that this method has perfomance implications, both in Realm and CoreData.

As for `swift_versions`, it's a new DSL from CocoaPods 1.7.0, which was not officially released, but has a [first release candidate](https://github.com/CocoaPods/CocoaPods/releases/tag/1.7.0.rc.1) at the moment. From my understanding, for old versions of CocoaPods this flag should not be fetched at all, so it should be backwards compatible, not sure why it's causing issues.

I will try to get this stuff done soon, so for now please use a fork with this fix if you need it.

**Comment by DenTelezhkin** [comment]
So, I've made changes I mentioned in previous post, and RealmStorage is now testable on CI.

I added two perfomance tests for `item(at:)` method of RealmStorage and CoreDataStorage - https://github.com/DenTelezhkin/DTModelStorage/blob/master/Tests/Realm/RealmStorageTestCase.swift#L309-L317
https://github.com/DenTelezhkin/DTModelStorage/blob/master/Tests/Specs/CoreDataStorageTestCase.swift#L150-L157

Unfortunately(or thankfully =)), those tests did not show perfomance problem, specifically for Realm getting an item seems to get reasonable results:

Testing device: iMac Late 2013 (3.5 GHz Intel Core i7)
For 10000 records getting an item takes at worst 0.0000506s on iPhone Xs simulator.

I'm aware that it's best to test perfomance on device and not simulator, however based on benchmark I once did for [EasyMapping and CoreData](https://github.com/lucasmedeirosleite/EasyMapping) the results are very similar, and simulator benchmarks are trustworthy.

I've added part of this PR, changing `items.count` to `numberOfItems`(https://github.com/DenTelezhkin/DTModelStorage/commit/713fd9c99ed60cfe777feb83ad61d8eb0a83e6bc), which seems to help a little bit, reducing worst time to 0.0000182.

Second part of actually going through subscript to results did not actually improve perfomance for this test, and actually worsened it for some runs. Based on those results I think that while `numberOfItems` is absolutely reasonable easy improvement, that will get into next release, actually changing Section interface and adding subscripts is not worth it at the moment.

What do you think? Maybe you have a better perfomance test or metric to measure this method perfomance?

**Comment by skydivedan** [comment]
OK, I'll get you some new performance tests.

The problem that I saw, delayed display of objects using DTCollectionView, about 10 seconds. When I put in the subscript routine, it became less than a second (I didn't measure the second one, I just noticed that there wasn't a noticeable delay).

I'll work on getting you empirical data. I'll get back to you on this next week.

**Comment by DenTelezhkin** [comment]
Thanks, that would be great!

**Comment by DenTelezhkin** [comment]
Hi!

I've made beta releases for next major versions of DTTable/CollectionViewManager as well as DTModelStorage, in which I've made improvements to specifically forbid perfomance problems like you encountered here.

In next releases `sections` and `items` properties have been made unavailable on a protocol level, and `section(atIndex:)`, `item(at:)` methods serve as replacement to prevent such perfomance hits in the future. I would like to thank you again for bringing this to attention, and please check out new releases, hope it works much faster now!

https://github.com/DenTelezhkin/DTTableViewManager/blob/master/Guides/7.0%20Migration%20Guide.md
https://github.com/DenTelezhkin/DTModelStorage/blob/master/Guides/8.0%20Migration%20Guide.md

**Pull request closed without merging**
